version: '3.8'

services:
  leadcms:
    image: leadcms/core:1.3.17-pre
    container_name: leadcms
    ports:
      - "8080:80"
    env_file:
      - ./apps/leadcms/.env
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: next-web
    ports:
      - "3000:3000"
    env_file:
      - ./apps/web/.env
    depends_on:
      - leadcms
    restart: unless-stopped
