// <copyright file="20250526062546_EmailTemplates.cs" company="LeadCMS Co. Ltd.">
// Copyright © LeadCMS Co. Ltd. All rights reserved.
// </copyright>

// <auto-generated/>
// ReSharper disable SA1118
// ReSharper disable StyleCop.SA1118
// StyleCop Suppression for SA1118: The parameter spans multiple lines
// Justification: Multi-line initializers improve readability for large data sets in migrations.

using System.Resources;
using LeadCMS.Plugin.Site.Data.Seed;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace LeadCMS.Plugin.Site.Migrations
{
    /// <inheritdoc />
    public partial class EmailTemplates : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "email_group",
                columns: new[] { "id", "created_at", "created_by_id", "created_by_ip", "created_by_user_agent", "language", "name", "source", "updated_at", "updated_by_id", "updated_by_ip", "updated_by_user_agent" },
                values: new object[] { 1, new DateTime(2025, 5, 26, 6, 25, 45, 803, DateTimeKind.Utc).AddTicks(870), null, null, null, "en", "Transactional", null, null, null, null, null });

            migrationBuilder.InsertData(
                table: "email_template",
                columns: new[]
                {
                    "id",
                    "body_template",
                    "created_at",
                    "created_by_id",
                    "created_by_ip",
                    "created_by_user_agent",
                    "email_group_id",
                    "from_email",
                    "from_name",
                    "language",
                    "name",
                    "retry_count",
                    "retry_interval",
                    "source",
                    "subject",
                    "updated_at",
                    "updated_by_id",
                    "updated_by_ip",
                    "updated_by_user_agent",
                },
                values: new object[,]
                {
                    {
                        1,
                        EmailTemplateData.ReadResource("En_Contact_Us.html"),
                        new DateTime(2025, 5, 26, 6, 25, 45, 803, DateTimeKind.Utc).AddTicks(960),
                        null,
                        null,
                        null,
                        1,
                        SitePlugin.Settings.SupportEmail,
                        "Support Team",
                        "en",
                        "Contact_Us",
                        0,
                        0,
                        null,
                        "New Contact Us Submission",
                        null,
                        null,
                        null,
                        null,
                    },
                    {
                        2,
                        EmailTemplateData.ReadResource("En_Acknowledgment.html"),
                        new DateTime(2025, 5, 26, 6, 25, 45, 803, DateTimeKind.Utc).AddTicks(1220),
                        null,
                        null,
                        null,
                        1,
                        SitePlugin.Settings.SupportEmail,
                        "Support Team",
                        "en",
                        "Acknowledgment",
                        0,
                        0,
                        null,
                        "Thank You for Contacting Us",
                        null,
                        null,
                        null,
                        null,
                    },
                    {
                        3,
                        EmailTemplateData.ReadResource("En_Subscription_Confirmation.html"),
                        new DateTime(2025, 5, 26, 6, 25, 45, 803, DateTimeKind.Utc).AddTicks(1250),
                        null,
                        null,
                        null,
                        1,
                        SitePlugin.Settings.SupportEmail,
                        "Support Team",
                        "en",
                        "Subscription_Confirmation",
                        0,
                        0,
                        null,
                        "Subscription Confirmed",
                        null,
                        null,
                        null,
                        null,
                    },
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "email_template",
                keyColumn: "id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "email_template",
                keyColumn: "id",
                keyValue: 2);

            migrationBuilder.DeleteData(
                table: "email_template",
                keyColumn: "id",
                keyValue: 3);

            migrationBuilder.DeleteData(
                table: "email_group",
                keyColumn: "id",
                keyValue: 1);
        }
    }
}
