// <copyright file="CoverImageGenerationService.cs" company="WavePoint Co. Ltd.">
// Licensed under the MIT license. See LICENSE file in the samples root for full license information.
// </copyright>

using AutoMapper;
using ImageMagick;
using LeadCMS.Constants;
using LeadCMS.Core.AIAssistance.Configuration;
using LeadCMS.Core.AIAssistance.DTOs;
using LeadCMS.Core.AIAssistance.Exceptions;
using LeadCMS.Core.AIAssistance.Interfaces;
using LeadCMS.Data;
using LeadCMS.DTOs;
using LeadCMS.Entities;
using LeadCMS.Helpers;
using LeadCMS.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace LeadCMS.Core.AIAssistance.Services;

public class CoverImageGenerationService : ICoverImageGenerationService
{
    private const int MaxSampleImages = 5;
    private const int DefaultSampleCount = 3;
    private const string DefaultFileName = "cover.png";
    private const string CoverNameSuffix = "cover";
    private readonly PgDbContext dbContext;
    private readonly IImageGenerationService imageGenerationService;
    private readonly ISettingService settingService;
    private readonly IMediaOptimizationService mediaOptimizationService;
    private readonly IMapper mapper;

    public CoverImageGenerationService(
        PgDbContext dbContext,
        IImageGenerationService imageGenerationService,
        ISettingService settingService,
        IMediaOptimizationService mediaOptimizationService,
        IMapper mapper)
    {
        this.dbContext = dbContext;
        this.imageGenerationService = imageGenerationService;
        this.settingService = settingService;
        this.mediaOptimizationService = mediaOptimizationService;
        this.mapper = mapper;
    }

    public async Task<MediaDetailsDto> GenerateCoverImageAsync(CoverImageGenerationRequest request)
    {
        Log.Information(
            "Starting cover image generation for content: {Title} (slug: {Slug})",
            request.ContentTitle,
            request.ContentSlug);

        // Step 1: Get sample cover images (user-provided or from recent content)
        var sampleImages = await GetSampleImagesAsync(request.SampleImagePaths);

        // Step 2: Get blog cover image requirements from settings
        var coverImageRequirements = await GetCoverImageRequirementsAsync();

        // Step 3: Get cover image size from settings
        var coverImageSize = await GetCoverImageSizeAsync();

        // Step 4: Determine optimal quality and parse size
        var (width, height, quality) = DetermineImageSettings(coverImageSize, coverImageRequirements);

        // Step 5: Build the generation prompt
        var prompt = BuildGenerationPrompt(request, sampleImages, coverImageRequirements);

        // Step 6: Generate the image
        var imageRequest = new ImageGenerationRequest
        {
            Prompt = prompt,
            Width = width,
            Height = height,
            Quality = quality,
            Style = "Auto",
            SampleImages = sampleImages.Select(s => new ImageInput
            {
                Data = s.Data,
                FileName = s.FileName,
                MimeType = s.MimeType,
            }).ToList(),
        };

        var imageResponse = await imageGenerationService.GenerateImageAsync(imageRequest);

        if (imageResponse.Images == null || imageResponse.Images.Count == 0)
        {
            throw new AIProviderException("CoverImageGeneration", "No image was generated by the AI provider.");
        }

        var generatedImage = imageResponse.Images.First();

        // Step 7: Get image data from response
        if (generatedImage.ImageData == null || generatedImage.ImageData.Length == 0)
        {
            throw new AIProviderException("CoverImageGeneration", "Generated image data is empty.");
        }

        // Step 8: Save to media storage
        var savedMedia = await SaveToMediaAsync(
            request.ContentSlug,
            request.ContentTitle,
            generatedImage.ImageData,
            request.ContentSlug);

        Log.Information(
            "Successfully generated and saved cover image for {Slug}. Media ID: {MediaId}",
            request.ContentSlug,
            savedMedia.Id);

        var result = mapper.Map<MediaDetailsDto>(savedMedia);
        result.Location = $"/api/media/{savedMedia.ScopeUid}/{savedMedia.Name}";
        return result;
    }

    public async Task<MediaDetailsDto> EditCoverImageAsync(CoverImageEditRequest request)
    {
        Log.Information(
            "Starting cover image edit for media: {CoverImageUrl}",
            request.CoverImageUrl);

        if (string.IsNullOrWhiteSpace(request.CoverImageUrl) ||
            !request.CoverImageUrl.StartsWith("/api/media/", StringComparison.OrdinalIgnoreCase))
        {
            throw new AIProviderException("CoverImageEdit", "CoverImageUrl must start with '/api/media/'.");
        }

        var (scopeUid, fileName) = ParseMediaUrl(request.CoverImageUrl);
        if (string.IsNullOrWhiteSpace(scopeUid) || string.IsNullOrWhiteSpace(fileName))
        {
            throw new AIProviderException("CoverImageEdit", "Unable to resolve the existing cover image location.");
        }

        var existingMedia = await dbContext.Media!
            .FirstOrDefaultAsync(m => m.ScopeUid == scopeUid && m.Name == fileName);

        if (existingMedia == null)
        {
            throw new AIProviderException("CoverImageEdit", "Existing cover image media was not found.");
        }

        var sampleImages = await GetSampleImagesAsync(request.SampleImagePaths, allowRecentFallback: false);
        sampleImages = sampleImages
            .Where(s => !string.Equals(s.ScopeUid, existingMedia.ScopeUid, StringComparison.OrdinalIgnoreCase) ||
                        !string.Equals(s.FileName, existingMedia.Name, StringComparison.OrdinalIgnoreCase))
            .ToList();

        var coverImageRequirements = await GetCoverImageRequirementsAsync();
        var coverImageSize = await GetCoverImageSizeAsync();
        var (width, height, quality) = DetermineImageSettings(coverImageSize, coverImageRequirements);

        var hasOriginal = existingMedia.OriginalData != null && existingMedia.OriginalData.Length > 0;
        var editImageData = hasOriginal ? existingMedia.OriginalData! : existingMedia.Data;
        var editImageMimeType = hasOriginal
            ? (existingMedia.OriginalMimeType ?? existingMedia.MimeType)
            : existingMedia.MimeType;
        var editImageName = EnsureImageFileName(
            hasOriginal ? existingMedia.OriginalName : existingMedia.Name,
            editImageMimeType);

        var prompt = BuildEditPrompt(request, sampleImages);

        var imageRequest = new ImageGenerationRequest
        {
            Prompt = prompt,
            Width = width,
            Height = height,
            Quality = quality,
            Style = "Auto",
            EditImage = new ImageInput
            {
                Data = editImageData,
                FileName = editImageName,
                MimeType = editImageMimeType,
            },
            SampleImages = sampleImages.Select(s => new ImageInput
            {
                Data = s.Data,
                FileName = s.FileName,
                MimeType = s.MimeType,
            }).ToList(),
        };

        var imageResponse = await imageGenerationService.GenerateImageAsync(imageRequest);

        if (imageResponse.Images == null || imageResponse.Images.Count == 0)
        {
            throw new AIProviderException("CoverImageEdit", "No image was generated by the AI provider.");
        }

        var generatedImage = imageResponse.Images.First();

        if (generatedImage.ImageData == null || generatedImage.ImageData.Length == 0)
        {
            throw new AIProviderException("CoverImageEdit", "Generated image data is empty.");
        }

        var updatedMedia = await UpdateExistingMediaAsync(existingMedia, request.ContentTitle, generatedImage.ImageData);

        Log.Information(
            "Successfully edited and saved cover image for {CoverImageUrl}. Media ID: {MediaId}",
            request.CoverImageUrl,
            updatedMedia.Id);

        var result = mapper.Map<MediaDetailsDto>(updatedMedia);
        result.Location = $"/api/media/{updatedMedia.ScopeUid}/{updatedMedia.Name}";
        return result;
    }

    private static string BuildGenerationPrompt(
        CoverImageGenerationRequest request,
        List<SampleImageInfo> sampleImages,
        string? coverImageRequirements)
    {
        var promptParts = new List<string>();

        // Main instruction
        promptParts.Add("Generate a professional blog cover image for the following article:");
        promptParts.Add($"Content Title: {request.ContentTitle}");
        promptParts.Add($"Content Description: {request.ContentDescription}");

        // User's specific prompt if provided
        if (!string.IsNullOrWhiteSpace(request.Prompt))
        {
            promptParts.Add($"\nSpecific requirements from user: {request.Prompt}");
        }

        // Style guidance from sample images
        if (sampleImages.Count > 0)
        {
            promptParts.Add("\nStyle guidance based on existing cover images in this blog:");
            var references = sampleImages
                .Select((s, i) =>
                {
                    var description = string.IsNullOrWhiteSpace(s.Description)
                        ? string.Empty
                        : $" — {s.Description}";
                    return $"- Sample {i + 1}: {s.FileName}{description}";
                })
                .ToList();

            if (references.Count > 0)
            {
                promptParts.AddRange(references);
                promptParts.Add("Please maintain visual consistency with these existing cover images.");
            }
            else
            {
                promptParts.Add("There are existing cover images in the blog. Generate an image that would fit well alongside them.");
            }
        }

        // Blog-specific cover image requirements
        if (!string.IsNullOrWhiteSpace(coverImageRequirements))
        {
            promptParts.Add($"\nBlog cover image style requirements: {coverImageRequirements}");
        }

        // General cover image best practices
        promptParts.Add("\nGeneral guidelines:");
        promptParts.Add("- Create a visually striking image suitable for a blog post cover");
        promptParts.Add("- Ensure the image has good visual hierarchy and composition");
        promptParts.Add("- Make sure the image is relevant to the article topic");
        promptParts.Add("- Use colors and composition that will work well with text overlays if needed");

        return string.Join("\n", promptParts);
    }

    private static string BuildEditPrompt(
        CoverImageEditRequest request,
        List<SampleImageInfo> sampleImages)
    {
        var promptParts = new List<string>
        {
            request.Prompt,
        };

        if (sampleImages.Count > 0)
        {
            promptParts.Add(string.Empty);
            promptParts.Add("Sample images:");

            var references = sampleImages
                .Select((s, i) =>
                {
                    var description = string.IsNullOrWhiteSpace(s.Description)
                        ? string.Empty
                        : $" — {s.Description}";
                    return $"- Reference {i + 1}: {s.FileName}{description}";
                })
                .ToList();

            if (references.Count > 0)
            {
                promptParts.AddRange(references);
            }
        }

        return string.Join("\n", promptParts.Where(part => !string.IsNullOrWhiteSpace(part)));
    }

    private static (string ScopeUid, string FileName) ParseMediaUrl(string url)
    {
        // Handle various URL formats:
        // /api/media/{scopeUid}/{fileName}
        // https://domain/api/media/{scopeUid}/{fileName}
        // {scopeUid}/{fileName}

        var path = url;

        // Remove domain prefix if present
        if (Uri.TryCreate(url, UriKind.Absolute, out var uri))
        {
            path = uri.AbsolutePath;
        }

        // Remove /api/media/ prefix if present
        const string apiMediaPrefix = "/api/media/";
        if (path.StartsWith(apiMediaPrefix, StringComparison.OrdinalIgnoreCase))
        {
            path = path.Substring(apiMediaPrefix.Length);
        }

        // Also handle without leading slash
        const string apiMediaPrefixNoSlash = "api/media/";
        if (path.StartsWith(apiMediaPrefixNoSlash, StringComparison.OrdinalIgnoreCase))
        {
            path = path.Substring(apiMediaPrefixNoSlash.Length);
        }

        // Now path should be {scopeUid}/{fileName}
        var lastSlash = path.LastIndexOf('/');
        if (lastSlash <= 0)
        {
            return (string.Empty, string.Empty);
        }

        var scopeUid = path.Substring(0, lastSlash);
        var fileName = path.Substring(lastSlash + 1);

        return (scopeUid, fileName);
    }

    private static (int? Width, int? Height, string Quality) DetermineImageSettings(
        string? coverImageSize,
        string? coverImageRequirements)
    {
        int? width = null;
        int? height = null;
        var quality = "low";

        // Parse size from MediaCoverSize setting (format: "WxH" e.g., "1024x1024")
        var (parsedWidth, parsedHeight) = MediaSizeHelper.ParseSize(coverImageSize);
        if (parsedWidth.HasValue && parsedHeight.HasValue)
        {
            width = parsedWidth;
            height = parsedHeight;
            Log.Information("Parsed cover image size from setting: {Width}x{Height}", width, height);
        }
        else if (!string.IsNullOrWhiteSpace(coverImageSize))
        {
            Log.Warning("Invalid MediaCoverSize format: {Size}. Expected 'WxH' (e.g., '1024x1024').", coverImageSize);
        }

        // Try to extract quality from cover image requirements setting
        if (!string.IsNullOrWhiteSpace(coverImageRequirements))
        {
            var requirementsLower = coverImageRequirements.ToLower();

            // Look for quality specifications
            if (requirementsLower.Contains("medium quality") || requirementsLower.Contains("medium-quality"))
            {
                quality = "medium";
            }

            if (requirementsLower.Contains("hd") || requirementsLower.Contains("high quality") || requirementsLower.Contains("high-quality"))
            {
                quality = "hd";
            }
        }

        Log.Information(
            "Determined image settings: Width={Width}, Height={Height}, Quality={Quality}",
            width?.ToString() ?? "Auto",
            height?.ToString() ?? "Auto",
            quality);

        return (width, height, quality);
    }

    private static byte[] ResizeToCover(byte[] data, int targetWidth, int targetHeight)
    {
        using var image = new MagickImage(data);

        var scale = Math.Max((double)targetWidth / image.Width, (double)targetHeight / image.Height);
        var resizedWidth = (int)Math.Ceiling(image.Width * scale);
        var resizedHeight = (int)Math.Ceiling(image.Height * scale);

        image.Resize((uint)resizedWidth, (uint)resizedHeight);

        var cropX = Math.Max(0, (resizedWidth - targetWidth) / 2);
        var cropY = Math.Max(0, (resizedHeight - targetHeight) / 2);

        image.Crop(new MagickGeometry(cropX, cropY, (uint)targetWidth, (uint)targetHeight));
        image.Page = new MagickGeometry(0, 0, 0, 0);

        return image.ToByteArray();
    }

    private static string EnsureImageFileName(string? fileName, string? mimeType)
    {
        var normalizedName = string.IsNullOrWhiteSpace(fileName) ? DefaultFileName : fileName;

        if (Path.HasExtension(normalizedName))
        {
            return normalizedName;
        }

        var extension = GetExtensionFromMimeType(mimeType);
        return Path.ChangeExtension(normalizedName, extension);
    }

    private static string GetExtensionFromMimeType(string? mimeType)
    {
        if (string.IsNullOrWhiteSpace(mimeType))
        {
            return ".png";
        }

        var normalized = mimeType.Trim().ToLowerInvariant();
        return normalized switch
        {
            "image/jpeg" or "image/jpg" => ".jpg",
            "image/webp" => ".webp",
            "image/gif" => ".gif",
            _ => ".png",
        };
    }

    private static void TrySetImageDimensions(
        Media media,
        string originalMimeType,
        byte[] originalData,
        string optimizedMimeType,
        byte[] optimizedData)
    {
        if (!originalMimeType.StartsWith("image/", StringComparison.OrdinalIgnoreCase) &&
            !optimizedMimeType.StartsWith("image/", StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        if (originalMimeType.StartsWith("image/", StringComparison.OrdinalIgnoreCase))
        {
            try
            {
                using var originalImage = new MagickImage(originalData);
                media.OriginalWidth = (int)originalImage.Width;
                media.OriginalHeight = (int)originalImage.Height;
            }
            catch
            {
                // Ignore dimension extraction failures
            }
        }

        if (optimizedMimeType.StartsWith("image/", StringComparison.OrdinalIgnoreCase))
        {
            try
            {
                using var optimizedImage = new MagickImage(optimizedData);
                media.Width = (int)optimizedImage.Width;
                media.Height = (int)optimizedImage.Height;
            }
            catch
            {
                // Ignore dimension extraction failures
            }
        }
    }

    private static SampleImageInfo CreateSampleImageInfo(Media media)
    {
        var hasOriginal = media.OriginalData != null && media.OriginalData.Length > 0;
        var data = hasOriginal ? media.OriginalData! : media.Data;
        var mimeType = hasOriginal ? (media.OriginalMimeType ?? media.MimeType) : media.MimeType;
        var fileName = hasOriginal ? (media.OriginalName ?? media.Name) : media.Name;

        return new SampleImageInfo
        {
            ScopeUid = media.ScopeUid,
            FileName = fileName,
            Description = media.Description,
            MimeType = mimeType,
            Data = data,
        };
    }

    private static string BuildUniqueCoverFileName(string baseName, string extension)
    {
        var normalizedBase = NormalizeCoverBaseName(baseName);
        normalizedBase = string.IsNullOrWhiteSpace(normalizedBase)
            ? CoverNameSuffix
            : normalizedBase.Slugify();
        if (string.IsNullOrWhiteSpace(normalizedBase))
        {
            normalizedBase = CoverNameSuffix;
        }

        var timestamp = DateTime.UtcNow.ToString("yyyyMMdd-HHmmss");
        if (normalizedBase.EndsWith($"-{CoverNameSuffix}", StringComparison.OrdinalIgnoreCase))
        {
            return $"{normalizedBase}-{timestamp}{extension}";
        }

        return $"{normalizedBase}-{CoverNameSuffix}-{timestamp}{extension}";
    }

    private static string NormalizeCoverBaseName(string? baseName)
    {
        if (string.IsNullOrWhiteSpace(baseName))
        {
            return string.Empty;
        }

        var normalized = baseName.Trim();
        var suffixPattern = new System.Text.RegularExpressions.Regex(
            $@"-{CoverNameSuffix}-\d{{8}}-\d{{6}}$",
            System.Text.RegularExpressions.RegexOptions.IgnoreCase);

        while (suffixPattern.IsMatch(normalized))
        {
            normalized = suffixPattern.Replace(normalized, string.Empty);
        }

        return normalized;
    }

    private async Task<List<SampleImageInfo>> GetSampleImagesAsync(
        List<string>? userProvidedPaths,
        bool allowRecentFallback = true)
    {
        var sampleImages = new List<SampleImageInfo>();

        if (userProvidedPaths != null && userProvidedPaths.Count > 0)
        {
            // Use user-provided sample images
            var pathsToUse = userProvidedPaths.Take(MaxSampleImages).ToList();

            foreach (var path in pathsToUse)
            {
                var (scopeUid, fileName) = ParseMediaUrl(path);
                if (string.IsNullOrWhiteSpace(scopeUid) || string.IsNullOrWhiteSpace(fileName))
                {
                    Log.Warning("Invalid sample image path format: {Path}. Expected 'scopeUid/fileName' or '/api/media/{scopeUid}/{fileName}'.", path);
                    continue;
                }

                var media = await dbContext.Media!
                    .FirstOrDefaultAsync(m => m.ScopeUid == scopeUid && m.Name == fileName);

                if (media != null)
                {
                    sampleImages.Add(CreateSampleImageInfo(media));
                }
                else
                {
                    Log.Warning("Sample image not found: {ScopeUid}/{FileName}", scopeUid, fileName);
                }
            }
        }

        // If no user-provided samples or none found, get from recent content with cover images
        if (sampleImages.Count == 0 && allowRecentFallback)
        {
            sampleImages = await GetRecentCoverImagesAsync(DefaultSampleCount);
        }

        return sampleImages;
    }

    private async Task<List<SampleImageInfo>> GetRecentCoverImagesAsync(int count)
    {
        var sampleImages = new List<SampleImageInfo>();

        // Find recent content with cover images, ordered by most recent update/creation
        var recentCoverUrls = await dbContext.Content!
            .Where(c => !string.IsNullOrEmpty(c.CoverImageUrl))
            .OrderByDescending(c => c.UpdatedAt ?? c.CreatedAt)
            .Take(count)
            .Select(c => c.CoverImageUrl)
            .ToListAsync();

        foreach (var coverUrl in recentCoverUrls)
        {
            // Parse the cover image URL to extract scopeUid and fileName
            // Expected format: /api/media/{scopeUid}/{fileName}
            if (string.IsNullOrEmpty(coverUrl))
            {
                continue;
            }

            var (scopeUid, fileName) = ParseMediaUrl(coverUrl);
            if (string.IsNullOrEmpty(scopeUid) || string.IsNullOrEmpty(fileName))
            {
                Log.Warning("Could not parse cover image URL: {CoverUrl}", coverUrl);
                continue;
            }

            var media = await dbContext.Media!
                .FirstOrDefaultAsync(m => m.ScopeUid == scopeUid && m.Name == fileName);

            if (media != null)
            {
                sampleImages.Add(CreateSampleImageInfo(media));
            }
        }

        Log.Information("Found {Count} recent cover images as samples", sampleImages.Count);
        return sampleImages;
    }

    private async Task<string?> GetCoverImageRequirementsAsync()
    {
        var requirements = await settingService.GetSystemSettingAsync(AiSettingKeys.BlogCoverInstructions);
        return string.IsNullOrWhiteSpace(requirements)
            ? null
            : requirements;
    }

    private async Task<string?> GetCoverImageSizeAsync()
    {
        return await settingService.GetSystemSettingAsync(SettingKeys.MediaCoverDimensions);
    }

    private async Task<Media> SaveToMediaAsync(string scopeUid, string? title, byte[] imageData, string? baseName)
    {
        var fileName = BuildUniqueCoverFileName(baseName ?? title ?? scopeUid, ".png");
        var originalExtension = ".png";
        var originalMimeType = "image/png";
        var settings = await mediaOptimizationService.GetSettingsAsync();
        var optimizationResult = await mediaOptimizationService.OptimizeAsync(new MediaOptimizationRequest
        {
            Data = imageData,
            FileName = fileName,
            Extension = originalExtension,
            MimeType = originalMimeType,
        });
        var coverResult = await ApplyCoverDimensionsIfNeeded(optimizationResult.Data, optimizationResult.MimeType);
        var optimizedName = Path.ChangeExtension(fileName, optimizationResult.Extension);
        // Always create a new media record to preserve history and avoid caching issues
        var newMedia = new Media
        {
            ScopeUid = scopeUid,
            Name = settings.EnableOptimisation ? optimizedName : fileName,
            OriginalName = settings.EnableOptimisation ? fileName : null,
            Size = coverResult.Size,
            Data = coverResult.Data,
            MimeType = settings.EnableOptimisation ? optimizationResult.MimeType : originalMimeType,
            Extension = settings.EnableOptimisation ? optimizationResult.Extension : originalExtension,
            OriginalData = settings.EnableOptimisation ? imageData : null,
            OriginalSize = settings.EnableOptimisation ? imageData.Length : null,
            OriginalExtension = settings.EnableOptimisation ? originalExtension : null,
            OriginalMimeType = settings.EnableOptimisation ? originalMimeType : null,
            Description = string.IsNullOrWhiteSpace(title) ? null : title,
            Tags = new[] { "cover" },
        };

        TrySetImageDimensions(
            newMedia,
            settings.EnableOptimisation ? originalMimeType : string.Empty,
            settings.EnableOptimisation ? imageData : Array.Empty<byte>(),
            optimizationResult.MimeType,
            coverResult.Data);

        await dbContext.Media!.AddAsync(newMedia);
        await dbContext.SaveChangesAsync();

        Log.Information("Created new cover image at {ScopeUid}/{FileName}", scopeUid, fileName);
        return newMedia;
    }

    private async Task<Media> UpdateExistingMediaAsync(Media existingMedia, string? title, byte[] imageData)
    {
        var baseName = Path.GetFileNameWithoutExtension(existingMedia.OriginalName ?? existingMedia.Name);
        baseName = NormalizeCoverBaseName(baseName);
        return await SaveToMediaAsync(existingMedia.ScopeUid, title ?? existingMedia.Description, imageData, baseName);
    }

    private async Task<CoverResizeResult> ApplyCoverDimensionsIfNeeded(byte[] data, string mimeType)
    {
        if (string.IsNullOrWhiteSpace(mimeType) ||
            !mimeType.StartsWith("image/", StringComparison.OrdinalIgnoreCase))
        {
            return new CoverResizeResult(data);
        }

        var coverDimensions = await GetCoverImageSizeAsync();
        var (targetWidth, targetHeight) = MediaSizeHelper.ParseSize(coverDimensions);

        if (!targetWidth.HasValue || !targetHeight.HasValue || targetWidth <= 0 || targetHeight <= 0)
        {
            return new CoverResizeResult(data);
        }

        try
        {
            return new CoverResizeResult(ResizeToCover(data, targetWidth.Value, targetHeight.Value));
        }
        catch
        {
            return new CoverResizeResult(data);
        }
    }

    private readonly struct CoverResizeResult
    {
        public CoverResizeResult(byte[] data)
        {
            Data = data;
            Size = data.LongLength;
        }

        public byte[] Data { get; }

        public long Size { get; }
    }

    private sealed class SampleImageInfo
    {
        public string ScopeUid { get; set; } = string.Empty;

        public string FileName { get; set; } = string.Empty;

        public string? Description { get; set; }

        public string? MimeType { get; set; }

        public byte[] Data { get; set; } = Array.Empty<byte>();
    }
}
